"""add user_repositories and remove user_id from repositories

Revision ID: 16ae8f1b33a1
Revises: 7a1c4f3e8b2d
Create Date: 2026-09-08 23:57:46.745687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ae8f1b33a1'
down_revision: Union[str, Sequence[str], None] = '7a1c4f3e8b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id')
    )
    op.create_index(op.f('ix_user_repositories_repository_id'), 'user_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_user_repositories_user_id'), 'user_repositories', ['user_id'], unique=False)
    op.drop_index(op.f('ix_repositories_github_url'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.create_unique_constraint(None, 'repositories', ['github_url'])
    op.drop_constraint(op.f('repositories_user_id_fkey'), 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('repositories_user_id_fkey'), 'repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'repositories', type_='unique')
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_index(op.f('ix_repositories_github_url'), 'repositories', ['github_url'], unique=True)
    op.drop_index(op.f('ix_user_repositories_user_id'), table_name='user_repositories')
    op.drop_index(op.f('ix_user_repositories_repository_id'), table_name='user_repositories')
    op.drop_table('user_repositories')
    # ### end Alembic commands ###
